### ISSUE TITLE
Accommodate Content-Security-Policy

### ISSUE THREAD

**Issue by BrucePerens** [crystal-loot/exception_page#17]
When this package reports an exception to the developer, it uses inline javascript. If the user has set a restrictive Content-Security-Policy, this is rejected. Solution: provide a way, per request, for the user to set a nonce. Add the nonce to the <script> tag, as in <script nonce="...">.

**Comment by matthewmcgarvey** [comment]
I don't know anything about these things so I'm just reading through some stuff. This seems to be about what you're referring to https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/

Of course MDN https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Here's a link to where rails generates the nonce and then exposes the method to be used in views (I'm not able to find where they set the `Content-Security-Policy` header, though.) https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_dispatch/http/content_security_policy.rb#L92-L100

This seems like it might be a pretty good example of adding CSP nonces https://github.com/phoenixframework/phoenix_live_dashboard/pull/223/files

**Comment by stakach** [comment]
This might be solved for you by #33

**Comment by jwoertink** [comment]
I think this is fixed now
