### ISSUE TITLE
Crystal 1.0.0 support

### ISSUE THREAD

**Issue by sdogruyol** [crystal-loot/exception_page#20]
Kemal build fails because of this shard hardly depending on Crystal 0.33.0

See the discussion here

https://github.com/kemalcr/kemal/pull/601#issuecomment-804671583

**Comment by Ash42Z** [comment]
Sorry to comment on a closed issue -
Since the change is only to master, any shard that depends on this and uses versioning instead of `branch: master` will not be able to use this "fix".

Do you think it's possible to create a new version tag (or update the old one) ?

**Comment by sdogruyol** [comment]
Yup, @Ash42Z is right. Can you guys release a new version please? @Sija @jwoertink

**Comment by jwoertink** [comment]
Yup. I'll cut a new release 👍

**Comment by jwoertink** [comment]
@Ash42Z @sdogruyol You can now update to 0.1.5!
