### ISSUE TITLE
Logo is displayed wrong on mobile

### ISSUE THREAD

**Issue by jwoertink** [crystal-loot/exception_page#32]
![Screenshot from 2022-02-08 14-57-53](https://user-images.githubusercontent.com/2391/153089752-1bd855dd-876a-488a-accc-4cf2c7ad72c2.png)

I think if we just make it the same 48x48 and centered, that would be fine.

**Comment by stakach** [comment]
this is also resolved in #33

**Comment by jwoertink** [comment]
It looks like it's just removed in mobile on that PR, right? (which I'm cool with :+1: )

**Comment by stakach** [comment]
there are 3 levels of media queries and the middle one is fixed which is what the screenshot above shows (at least in my testing)
the smallest one previously also hid the logo from what I can see

**Comment by jwoertink** [comment]
Fixed by https://github.com/crystal-loot/exception_page/pull/33
