### ISSUE TITLE
Decouple from `HTTP:ServerContext`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-loot/exception_page#48]
Currently the `ExceptionPage` type is tightly coupled to `HTTP::Server::Context`: https://github.com/crystal-loot/exception_page/blob/a5261c2e7d087f8f02dab39a3a7d0c7de93d12a1/src/exception_page.cr#L72-L80

This makes it harder to use in cases where this specific object is unavailable, but the raw data being fetched off of it is available. It would be fairly straightforward to change `#initialize` to accept the raw values directly, and have a `self.new` overload to handle the current case for backwards compatibility.

**Comment by jwoertink** [comment]
Sounds good to me!

**Comment by Blacksmoke16** [comment]
This is actually not as straightforward to do nicely in a backwards compatible way. The overload that accepts the context and exception uses an instance method `backstrace` to get the configuration for backtracer. However given its an instance method its not available within the class scope. I.e. within `self.new`.

I can probably work around this, or if breaking changes are okay we can also go that route...

**Comment by jwoertink** [comment]
Since this shard isn't 1.0, I think breaking changes are ok. We can just bump it to 0.5.0 and make note of it.
