### ISSUE TITLE
DOM based XSS via params

### ISSUE THREAD

**Issue by bararchy** [crystal-loot/exception_page#9]
It seems the exception page parses params dynamically in the DOM, it's really simple to add any param to the query and use the basic XXS token like `<script>alert(1)</script>` to execute the attack.

![Screenshot at 15-55-45](https://user-images.githubusercontent.com/1631073/74940231-cda00580-53f9-11ea-80fc-5650ec079a80.png)

**Comment by paulcsmith** [comment]
Thanks! We can html escape those before showing them. 

Not super urgent since this is development only but agree we should fix it anyway!

**Comment by bararchy** [comment]
@paulcsmith all good, I'm building a vulnerable app in Crystal and was running our scanner on it to verify and it found this one on the way XD so I figured I better report it.

**Comment by paulcsmith** [comment]
That’s awesome! Sounds like it’s working :D
